version: '3'
services:
  app:
    build: ./
    volumes:
      - ./:/app
      - /app/node_modules
      - ../puppeteer-howstat:/puppeteer-howstat
      - ../puppeteer-cric-data:/app/data
    container_name: puppeteer-cricbuzz
    env_file:
      - .env.local